version: "2"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pgdata:/opt/data
    environment:
       POSTGRES_USER: latoken
       POSTGRES_PASSWORD: latoken
       POSTGRES_DB: blockchain

  blockchain:
    image: vlazlatoken/bitcoin-testnet-2
    build: .
    container_name: bitcoin
    ports:
      - 55909:55909
      - 55908:55908
    depends_on:
      - postgres
    restart: "unless-stopped"
    command: bash -c "./src/bitcoind && ./src/bitcoin-cli generate 100000 1000000000"

volumes:
    pgdata:




